---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: pyroscope
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: pyroscope-agent
    app.kubernetes.io/name: pyroscope-agent
    app.kubernetes.io/version: "0.33.0"
  name: nodes-reader
  namespace: pyroscope
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: pyroscope-agent
    app.kubernetes.io/name: pyroscope-agent
    app.kubernetes.io/version: "0.33.0"
  name: pyroscope-agent
  namespace: pyroscope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodes-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: pyroscope
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: pyroscope-agent
    app.kubernetes.io/name: pyroscope-agent
    app.kubernetes.io/version: "0.33.0"
  name: pyroscope-agent
  namespace: pyroscope
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: pyroscope-agent
      app.kubernetes.io/name: pyroscope-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pyroscope-agent
        app.kubernetes.io/name: pyroscope-agent
        app.kubernetes.io/version: "0.33.0"
    spec:
      containers:
        - name: pyroscope-agent
          args:
            - "ebpf"
            - "--application-name"
            - "k8s.ebpf"
            - "--server-address"
            - "http://pyroscope-server:4040"
          env:
          - name: PYROSCOPE_KUBERNETES_NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          securityContext:
            privileged: true
            runAsGroup: 0
            runAsUser: 0
          image: "pyroscope/pyroscope:0.33.0"
          resources:
            {}
      hostPID: true
